using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.IO;
using excel = Microsoft.Office.Interop.Excel;

namespace okul_kayıtt
{
    public partial class Form15 : Form
    {
        public Form15()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            bolumlerTableAdapter1.Fill(kayıtDataSet1.bolumler);
        }

        private void Form15_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'kayıtDataSet.fakulte' table. You can move, or remove it, as needed.
            this.fakulteTableAdapter.Fill(this.kayıtDataSet.fakulte);

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                if (saveFileDialog1.ShowDialog() == DialogResult.OK)
                {
                    StreamWriter sw = new StreamWriter(saveFileDialog1.FileName, true, Encoding.UTF32);
                    int sayı = dataGridView1.SelectedRows.Count;
                    for (int i = 0; i < sayı; i++)
                    {
                        string a = dataGridView1.SelectedRows[i].Cells[0].Value.ToString() + dataGridView1.SelectedRows[i].Cells[1].Value.ToString();

                        sw.WriteLine(a.ToString());
                    }
                    sw.Close();
                }
                MessageBox.Show("Başarı İle Aktarıldı");
            }
            catch (Exception ee)
            {
                MessageBox.Show("Kayıt Aktarılamadı");
                MessageBox.Show(ee.Message.ToString());
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            excel.Application dosya = new excel.Application();//excel acar
            dosya.Visible = true;//exceli gösterir 
            object a = Type.Missing;
            excel.Workbook kitap = dosya.Workbooks.Add(a);//calısma sayfası olusturur.
            excel.Worksheet sayfa = (excel.Worksheet)kitap.Sheets[1];//calısma alanı çalısma sayfası 1 rakamı kacıncı sayfada calısacaksak
            int sutun = 1;//excele yazdıracagımız satır
            int satır = 1;//excele yazdıracagımız sutun
            for (int i = 0; i < dataGridView1.Columns.Count; i++)//5 alan varsa 5 dönecek
            {
                excel.Range hücre = (excel.Range)sayfa.Cells[satır, sutun + i];//alan hangi alan hücre biri sıfırdan digeri biroldugu için +2
                hücre.Value2 = dataGridView1.Columns[i].HeaderText;//alanın o degerine
            }
            satır++;
            for (int z = 0; z < dataGridView1.Rows.Count; z++)
            {
                for (int i = 0; i < dataGridView1.Columns.Count; i++)
                {
                    try
                    {
                        excel.Range hücre = (excel.Range)sayfa.Cells[satır + z, sutun + i];
                        hücre.Value2 = dataGridView1[i, z].Value;
                    }
                    catch (Exception bb)
                    {

                        MessageBox.Show(bb.Message.ToString());
                    }

                }
            }
        }
    }
}
